//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Import
    {
        public int ImportID { get; set; }
        public Nullable<System.DateTime> ImportDate { get; set; }
        public Nullable<int> PCode { get; set; }
        public Nullable<int> CatId { get; set; }
        public Nullable<int> SupId { get; set; }
        public Nullable<int> ImportQTY { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Product Product { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
